# Site settings
title: Kenneth EZUKWOKE
email: kenneth.ezukwoke@datategy.net"
description: Webpage of Kenneth EZUKWOKE
baseurl: ""  # empty since your site is at the root
url: "https://kennedyczar.github.io"  # your site's domain

encoding: UTF-8

# Google analytics ID: Remove or use your own!
#google_analytics: UA-167467135-1
#google_analytics_4: G-02KDGRRB2T
#google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Kenneth EZUKWOKE, Ph.D<br/>
    Research & Development Engineer<br/>
    <a href="https://www.mines-stetienne.fr/recherche/centres-et-departements/departement-genie-mathematique-et-industriel/" target="_blank">Génie mathématique et industriel</a><br/>
    Écoles des Mines de Saint-Étienne

location: >
  <a href="https://www.mines-stetienne.fr/recherche/centres-et-departements/departement-genie-mathematique-et-industriel/" target="_blank">Institute Henri FAYOL</a><br/>
  29 Rue Pierre et Dominique Ponchardier <br/>
  Écoles des Mines de Saint-Étienne<br/>
  Saint-Étienne, FR

contact: >
    <a href="mailto:kenneth.ezukwoke@datategy.net" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Kenneth via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: publications
  - name: talks
  - name: research
  - name: podcast
#  - name: software
# - name: team
# - name: teaching

defaults:
  - scope:
      path: "assets/css"
    values:
      sass:
        style: compressed


sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never


include:
  - _sass
  - assets
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-sitemap

scholar:

  last_name: EZUKWOKE
  first_name: [Kenneth]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache
  - .jekyll-cache
